# Generated by Django 3.1.2 on 2020-10-16 02:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('context', models.TextField()),
                ('zan_num', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='user.user')),
            ],
        ),
    ]
