# Generated by Django 3.1.2 on 2020-10-13 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True)),
                ('passwords', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('grades', models.FloatField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)])),
                ('status', models.IntegerField(choices=[(0, '老师'), (1, '学生')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('descriptions', models.TextField()),
                ('demo_scripts', models.TextField()),
                ('c_time', models.DateField(auto_now=True)),
                ('to_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('context', models.TextField()),
                ('title', models.CharField(max_length=20)),
                ('to_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='user.user')),
            ],
        ),
    ]
