# Generated by Django 3.1.2 on 2020-10-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, '老师'), (0, '学生')], default=0),
        ),
    ]
